name: Main Workflow
on: push
jobs:  
  test:
    runs-on: windows-latest
    steps: 
      - name: Getting repository code
        uses: actions/checkout@v3
      - name: Getting dependencies
        run: npm i ci
      - name: Testing funcs
        run: npm run test
      







